//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasureMyPike
{
    using Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Catch> Catch { get; set; }
        public virtual DbSet<Fish> Fish { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<MediaData> MediaData { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Lures> Lures { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<WeatherData> WeatherData { get; set; }
        public virtual DbSet<UserConnections> UserConnections { get; set; }
    }
}
