//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasureMyPike.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatchDO()
        {
            this.Media = new HashSet<MediaDO>();
        }
    
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual UserDO User { get; set; }
        public virtual CommentDO Comment { get; set; }
        public virtual FishDO Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaDO> Media { get; set; }
        public virtual LocationDO Location { get; set; }
        public virtual LureDO Lures { get; set; }
        public virtual StatisticsDO Statistics { get; set; }
        public virtual WeatherDataDO WeatherData { get; set; }
    }
}
