//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasureMyPike.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaDataDO
    {
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public int Length { get; set; }
    
        public virtual MediaDO Media { get; set; }
    }
}
