//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasureMyPike.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDO> User { get; set; }
        public virtual DbSet<CatchDO> Catch { get; set; }
        public virtual DbSet<FishDO> Fish { get; set; }
        public virtual DbSet<CommentDO> Comment { get; set; }
        public virtual DbSet<MediaDO> Media { get; set; }
        public virtual DbSet<MediaDataDO> MediaData { get; set; }
        public virtual DbSet<LocationDO> Location { get; set; }
        public virtual DbSet<BrandDO> Brand { get; set; }
        public virtual DbSet<LureDO> Lure { get; set; }
        public virtual DbSet<StatisticsDO> Statistics { get; set; }
        public virtual DbSet<WeatherDataDO> WeatherData { get; set; }
        public virtual DbSet<SecurityDO> Security { get; set; }
        public virtual DbSet<TackleBoxDO> TackleBox { get; set; }
    }
}
